### PR TITLE
Issue 41: add local `fromEvent` module

### PR DESCRIPTION
**Pull request by Frikki**
Remove `rx-dom` dependency.
Add `fromEvent` local module.

References #41, #42

### CODE REVIEW

**Comment by Frikki** [comment]
Any comments, @staltz ?

**Comment by staltz** [comment]
Ah great, I'll merge this. Sorry for not commenting earlier, I sometimes don't get email notification from github (it seems like a bug), I don't know why.

**Comment by Frikki** [comment]
I cannot express enough thumbs up for this :+1: :+1: :+1: :+1: :+1: :dancer:

**Comment by staltz** [comment]
I'll go test it and release a new minor version

**Pull request merged**
