### PR TITLE
Change undefined check

### PR DESCRIPTION
**Pull request by bloodyKnuckles**
Change the b and c parameter undefined check to allow numbers 0 to pass and not be ignored.

See [related issue](https://github.com/cyclejs/core/issues/320).

### CODE REVIEW

**Comment by staltz** [comment]
Thanks for this PR. :)

Can you also include a test that prior to the fix would fail but after the fix, passes? We usually add both tests and fixes together.

**Comment by bloodyKnuckles** [comment]
Using [*render.js*](https://github.com/cyclejs/dom/blob/master/test/browser/render.js#L49) as an example, here's a test that does not pass before this pull request, but does pass with the pull request changes:
```
  it('should render 0', function (done) {
    function app() {
      return {
        DOM: Rx.Observable.of(div('.my-class', 0))
      };
    }

    const {sinks, sources, run} = Cycle(app, {
      DOM: makeDOMDriver(createRenderTarget())
    });

    let dispose;
    sources.DOM.select(':root').elements().skip(1).take(1).subscribe(function (root) {
      const divEl = root.querySelector('.my-class');
      assert.strictEqual(divEl.textContent, '0');
      setTimeout(() => {
        dispose();
        done();
      });
    });
    dispose = run();
  });
```

I don't know how to include the test in this pull request. Or do I make another pull request and add this test to [*render.js*](https://github.com/cyclejs/dom/blob/master/test/browser/render.js)?

**Comment by mightyiam** [comment]
@bloodyKnuckles to include it in the pull request, you commit to the same branch. That is, `bloodyKnuckles:patch-2`

**Comment by bloodyKnuckles** [comment]
@mightyiam Thanks. Piece of cake, once I figured out I had to go to my github account to access the `bloodyKnuckes:patch-2` branch. : )

**Comment by staltz** [comment]
Thanks for the PR!

**Pull request merged**
