### PR TITLE
Fix: Nesting Observables in Vtree nodes more than one level deep

### PR DESCRIPTION
**Pull request by laszlokorte**
https://github.com/cyclejs/cycle-dom/issues/71

### CODE REVIEW

**Comment by staltz** [comment]
What's with the commit storm in this PR?

**Comment by laszlokorte** [comment]
Sorry, selected the wrong branch... I will fix it

**Comment by staltz** [comment]
I think you need to target `auto-scope` branch.

**Comment by laszlokorte** [comment]
Now this PR targets the master branch.
I created another PR for the autoscope branch.

**Comment by staltz** [comment]
Since this is for the master branch and it's the same changes as for `auto-scope` branch, I won't merge this. Your changes will go into v8.0.0-rc6, and soon v8.0.0 itself will be released (I'm sure Cycle Nested is published still in 2015).

**Pull request closed without merging**
